### ISSUE TITLE
Can we get a second version with a more complex model?

### ISSUE THREAD

**Issue by Manugr21** [TasinIshmam/blog-backend-rest-api-nestjs-prisma#1]
Your article was awesome!!

But can you show proper way of using connections, and connect on create, create many on create, etc. I'm having tons of trouble figuring out how to use these functions and creating DTO's for these use cases.

**Comment by TasinIshmam** [comment]
Hi @Manugr21  

Thanks for the kind words. I understand your point about showing more complicated relations. That's something we are planning to do in some of the coming articles in the series. 

Just to clarify, are you looking for clarification on how to: 

1. Create DTOs for connections/nested relations (`include` and `connect` use cases in Prisma-specific syntax)
2. How to handle create many 

Is there anything else that you'd like to see?

**Comment by Manugr21** [comment]
Thanks for your time @TasinIshmam
I would really love to see proper examples of complex models on graphql, authentication and authorization, proper logging and more big company needs.

**Comment by TasinIshmam** [comment]
@Manugr21  I'll be sure to let you know once we have more content 😄

For GraphQL, this example might be useful: https://github.com/notiz-dev/nestjs-prisma-starter

**Comment by TasinIshmam** [comment]
Hey @Manugr21, 

We have a [new article](https://www.prisma.io/blog/nestjs-prisma-relational-data-7D056s1kOabc) that talks about handling relations in a NestJS REST API. 

I think this covers the use cases you were asking for.
